<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by SAN Business Consultants for RAPTOR phase 2
 * Open Source VA Innovation Project 2011-2015
 * VA Innovator: Dr. Jonathan Medverd
 * SAN Implementation: Andrew Casertano, Frank Font, et al
 * Contacts: acasertano@sanbusinessconsultants.com, ffont@sanbusinessconsultants.com
 * ------------------------------------------------------------------------------------
 * 
 * A data layer module that gets content for the RAPTOR application. 
 *
 */

defined('RAPTOR_EWDVISTA_MODULE_PATH')
    or define('RAPTOR_EWDVISTA_MODULE_PATH', dirname(__FILE__));  


function raptor_ewdvista_help($path, $arg) 
{
  switch ($path)
  {
    case "admin/help#raptor_ewdvista":
      return '<p>'.  t("Integration with VistA for the RAPTOR application using EWD"). '</p>';
      break;
  }
}

function raptor_ewdvista_menu() 
{
    $items = array();
    $items['ewdvista/diagnostic1'] = array(
      'title' => t('Developer Diagnostic Page1'),
      'page callback' => 'raptor_ewdvista_diagnostic1_form',
      'access arguments' => array('access content'),
      'access callback' => TRUE,        
      'description' => t('Developer Diagnostic1 Page'),
      'type' => MENU_CALLBACK,
      'file' => 'DiagnosticPage1.php',
      'file path' => '/sites/all/modules/raptor_ewdvista/form/',
    );
    $items['ewdvista/diagnostic2'] = array(
      'title' => t('Developer Diagnostic Page2'),
      'page callback' => 'raptor_ewdvista_diagnostic2_form',
      'access arguments' => array('access content'),
      'access callback' => TRUE,        
      'description' => t('Developer Diagnostic Page2'),
      'type' => MENU_CALLBACK,
      'file' => 'DiagnosticPage2.php',
      'file path' => '/sites/all/modules/raptor_ewdvista/form/',
    );
    return $items;
}

function raptor_ewdvista_diagnostic1_form() 
{
    return drupal_get_form('raptor_ewdvista_diagnostic1_form_builder');
}

function raptor_ewdvista_diagnostic2_form() 
{
    return drupal_get_form('raptor_ewdvista_diagnostic2_form_builder');
}

function raptor_ewdvista_diagnostic_root_pagebuilder($oPage, $form, &$form_state)
{
    try
    {
        if(isset($_GET['disabled']))
        {
            $disabled_tx = strtoupper(trim($_GET['disabled']));
        } else {
            $disabled_tx = 'FALSE';
        }
        if(isset($_GET['action']))
        {
            $action_tx = strtoupper(trim($_GET['action']));
        } else {
            $action_tx = '';
        }
        if(isset($form_state['values']))
        {
            $myvalues = $form_state['values'];    
        } else {
            $myvalues = $oPage->getFieldValues();
        }
        $myvalues['action'] = $action_tx;
        $myvalues['build_ts'] = time();
        $disabled = ($disabled_tx == 'TRUE');
        return $oPage->getForm($form, $form_state, $disabled, $myvalues);
    } catch (\Exception $ex) {
        $msg = "Failed raptor_ewdvista_diagnostic1_form_builder because ".$ex;
        error_log($msg);
        drupal_set_message($msg,'error');
        throw new \Exception($msg,99777,$ex);
    }
}

/**
 * Build the page
 */
function raptor_ewdvista_diagnostic1_form_builder($form, &$form_state)
{
    try
    {
        $oPage = new \raptor_ewdvista\DiagnosticPage1();
        return raptor_ewdvista_diagnostic_root_pagebuilder($oPage, $form, $form_state);
    } catch (\Exception $ex) {
        $msg = "Failed raptor_ewdvista_diagnostic1_form_builder because ".$ex;
        error_log($msg);
        drupal_set_message($msg,'error');
        throw new \Exception($msg,99777,$ex);
    }
}
function raptor_ewdvista_diagnostic2_form_builder($form, &$form_state)
{
    try
    {
        $oPage = new \raptor_ewdvista\DiagnosticPage2();
        return raptor_ewdvista_diagnostic_root_pagebuilder($oPage, $form, $form_state);
    } catch (\Exception $ex) {
        $msg = "Failed raptor_ewdvista_diagnostic2_form_builder because ".$ex;
        error_log($msg);
        drupal_set_message($msg,'error');
        throw new \Exception($msg,99777,$ex);
    }
}

function raptor_ewdvista_diagnostic1_form_builder_validate($form, &$form_state) 
{
    try
    {
        $oPage = new \raptor_ewdvista\DiagnosticPage1();
        $myvalues = $form_state['values'];
        $myvalues['validate_ts'] = time();
        return $oPage->looksValid($form, $myvalues);
    } catch (\Exception $ex) {
        $msg = "Failed validate because ".$ex;
        error_log($msg);
        drupal_set_message($msg,'error');
        return FALSE;
    }
}
function raptor_ewdvista_diagnostic2_form_builder_validate($form, &$form_state) 
{
    try
    {
        $oPage = new \raptor_ewdvista\DiagnosticPage2();
        $myvalues = $form_state['values'];
        $myvalues['validate_ts'] = time();
        return $oPage->looksValid($form, $myvalues);
    } catch (\Exception $ex) {
        $msg = "Failed validate because ".$ex;
        error_log($msg);
        drupal_set_message($msg,'error');
        return FALSE;
    }
}


/**
 * Process the submitted form
 */
function raptor_ewdvista_diagnostic1_form_builder_submit($form, &$form_state) 
{
    try
    {
        $form_state['rebuild'] = TRUE;  //Stay on same page
        $oPage = new \raptor_ewdvista\DiagnosticPage1();
        $form_state['values']['submit_ts'] = time();
        $oPage->updateDatabase($form_state);
    } catch (\Exception $ex) {
        error_log("Failed raptor_ewdvista_diagnostic1_form_submit because ".$ex);
        drupal_set_message($ex,'error');
    }
}
function raptor_ewdvista_diagnostic2_form_builder_submit($form, &$form_state) 
{
    try
    {
        $form_state['rebuild'] = TRUE;  //Stay on same page
        $oPage = new \raptor_ewdvista\DiagnosticPage2();
        $form_state['values']['submit_ts'] = time();
        $oPage->updateDatabase($form_state);
    } catch (\Exception $ex) {
        error_log("Failed raptor_ewdvista_diagnostic2_form_submit because ".$ex);
        drupal_set_message($ex,'error');
    }
}

