name = RAPTOR Protocol
description = The RAPTOR protcol layout
template = protocol-layout
preview = preview.png

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; ========================================
; Stylesheets
; ========================================


; ========================================
; Scripts
; ========================================
scripts[] = js/jquery-ui-1.10.3.min.js
scripts[] = js/modernizr-2.5.3.min.js
scripts[] = js/protocol.js
;scripts[] = js/d3.min.js
;scripts[] = js/raptor-charts.js
scripts[] = js/jquery.scrollTo.min.js
scripts[] = js/jquery.dataTables.js
