<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by SAN Business Consultants for RAPTOR phase 2
 * Open Source VA Innovation Project 2011-2015
 * VA Innovator: Dr. Jonathan Medverd
 * SAN Implementation: Andrew Casertano, Frank Font, et al
 * Contacts: acasertano@sanbusinessconsultants.com, ffont@sanbusinessconsultants.com
 * ------------------------------------------------------------------------------------
 * Copyright 2015 SAN Business Consultants, a Maryland USA company (sanbusinessconsultants.com)
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------------
 * A image viewing integration module for the RAPTOR application. 
 */

function raptor_imageviewing_help($path, $arg) 
{
  switch ($path)
  {
    case "admin/help#raptor_imageviewing":
        return '<p>'.  t("Integrates image viewing package.") .'</p>';
        break;
  }
}

function raptor_imageviewing_menu() 
{
    $items = array();
    
    $items['raptor/imageviewing/runtests'] = array(
      'title' => t('Image Viewing Test'),
      'page callback' => 'raptor_imageviewing_runtests_form',
      'access arguments' => array('access content'),
      'access callback' => TRUE,        
      'description' => t('Test image viewing integration'),
      'type' => MENU_CALLBACK,
    );

    return $items;
}

function raptor_imageviewing_runtests_form() 
{
    return drupal_get_form("raptor_imageviewing_runtests_form_builder");
}

function raptor_imageviewing_runtests_form_builder($form, &$form_state)
{
	throw new \Exception('Feature not yet implemented');
}

function raptor_imageviewing_runtests_form_builder_submit($form, &$form_state)
{
	throw new \Exception('Feature not yet implemented');
}


/**
 * Call the VIX to get image metadata.
 * @param type $oContext
 * @param type $patientDFN
 * @param type $patientICN
 * @param type $reportID
 * @param type $caseNumber
 * @return array of image metadata
 */
function raptor_imageviewing_getAvailImageMetadata($oContext, $patientDFN, $patientICN, $reportID, $caseNumber)
{
    require_once ('core/VixDao.php');
    $oVixDao = $oContext->getVixDao();
    $aImageInfo = $oVixDao->getImageInfoForReport($patientDFN, $patientICN, $reportID, $caseNumber);
    return $aImageInfo;
}


