<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by SAN Business Consultants
 * Designed and implemented by Frank Font (ffont@sanbusinessconsultants.com)
 * In collaboration with Andrew Casertano (acasertano@sanbusinessconsultants.com)
 * Open source enhancements to this module are welcome!  Contact SAN to share updates.
 *
 * Copyright 2014 SAN Business Consultants, a Maryland USA company (sanbusinessconsultants.com)
 *
 * Licensed under the GNU General Public License, Version 2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/copyleft/gpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------------
 *
 * This is a simple decision support engine module for Drupal.
 */


/** 
 * Implements hook_help. 
 * 
 * Displays help and module information. 
 * 
 * @param path  
 *   Which path of the site we're using to display help 
 * @param arg  
 *   Array that holds the current path as returned from arg() function 
 */
function simplerulesengine_ui_help($path, $arg) 
{
    $contributemsg = 'Contact Frank Font or Andrew Casertano at <a href="http://sanbusinessconsultants.com/">SAN Business Consultants</a> to contribute to this open source project or to ask about decision support consulting services.';
    switch ($path)
    {
      case "admin/help#simplerulesengine_ui":
          return '<p>'. t("This module contains user interface elements for working with the simple rules engine core.  The features of this modules are for developers to access programatically.") .'</p>'
                .'<p>'.t($contributemsg).'</p>';
          break;
    }
}

function simplerulesengine_ui_menu() 
{
    $items = array();
    return $items;
}





