<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by SAN Business Consultants for RAPTOR phase 2
 * Open Source VA Innovation Project 2011-2014
 * VA Innovator: Dr. Jonathan Medverd
 * SAN Implementation: Andrew Casertano, Frank Font, et al
 * Contacts: acasertano@sanbusinessconsultants.com, ffont@sanbusinessconsultants.com
 * ------------------------------------------------------------------------------------
 *  
 * A image viewing integration module for the RAPTOR application. 
 *
 */

function raptor_imageviewing_help($path, $arg) 
{
  switch ($path)
  {
    case "admin/help#raptor_imageviewing":
        return '<p>'.  t("Integrates image viewing package.") .'</p>';
        break;
  }
}

function raptor_imageviewing_menu() 
{
    $items = array();
    
    $items['raptor/imageviewing/runtests'] = array(
      'title' => t('Image Viewing Test'),
      'page callback' => 'raptor_imageviewing_runtests_form',
      'access arguments' => array('access content'),
      'access callback' => TRUE,        
      'description' => t('Test image viewing integration'),
      'type' => MENU_CALLBACK,
    );

    return $items;
}

function raptor_imageviewing_runtests_form() 
{
    return drupal_get_form("raptor_imageviewing_runtests_form_builder");
}

function raptor_imageviewing_runtests_form_builder($form, &$form_state)
{
	throw new \Exception('Feature not yet implemented');
}

function raptor_imageviewing_runtests_form_builder_submit($form, &$form_state)
{
	throw new \Exception('Feature not yet implemented');
}


/**
 * Call the VIX to get image metadata.
 * @param type $oContext
 * @param type $patientDFN
 * @param type $patientICN
 * @param type $reportID
 * @param type $caseNumber
 * @return array of image metadata
 */
function raptor_imageviewing_getAvailImageMetadata($oContext, $patientDFN, $patientICN, $reportID, $caseNumber)
{
    require_once ('core/VixDao.php');
    $oVixDao = $oContext->getVixDao();
    $aImageInfo = $oVixDao->getImageInfoForReport($patientDFN, $patientICN, $reportID, $caseNumber);
    return $aImageInfo;
}


