<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by SAN Business Consultants for RAPTOR phase 2
 * Open Source VA Innovation Project 2011-2015
 * VA Innovator: Dr. Jonathan Medverd
 * SAN Implementation: Andrew Casertano, Frank Font, et al
 * Contacts: acasertano@sanbusinessconsultants.com, ffont@sanbusinessconsultants.com
 * ------------------------------------------------------------------------------------
 * 
 * A data layer module that gets content for the RAPTOR application. 
 *
 */

require_once 'core/UserInfo.php';
require_once 'core/Context.php';
require_once 'core/TicketTrackingData.php';

defined('RAPTOR_DATALAYER_MODULE_PATH')
    or define('RAPTOR_DATALAYER_MODULE_PATH', dirname(__FILE__));  

function raptor_datalayer_help($path, $arg) 
{
  switch ($path)
  {
    case "admin/help#raptor_datalayer":
      return '<p>'.  t("Returns relevant data for the RAPTOR application"). '</p>';
      break;
  }
}

function raptor_datalayer_menu() 
{
    $items = array();
    
    $items['admin/config/raptor_datalayer'] = array(
      'title' => t('Edit Datalayer Configuration'),
      'page callback' => 'raptor_datalayer_edit_config_form',
      'access arguments' => array('access content'),
      'access callback' => TRUE,        
      'description' => t('Edit Datalayer Configuration Form'),
      'type' => MENU_CALLBACK,
      'file' => 'EditDatalayerConfigPage.php',
      'file path' => '/sites/all/modules/raptor_datalayer/form/',
    );

    $items['getdaoruntimemetrics'] = array(
      'title' => t('Get DAO Runtime Metrics'),
      'page callback' => 'raptor_datalayer_getdaoruntimemetrics_form',
      'access arguments' => array('access content'),
      'access callback' => TRUE,        
      'description' => t('Get DAO Runtime Metrics'),
      'type' => MENU_CALLBACK,
      'file' => 'EhrDaoRuntimeMetrics.php',
      'file path' => '/sites/all/modules/raptor_datalayer/core/',
    );
    
    return $items;
}


function raptor_datalayer_edit_config_form() 
{
    return drupal_get_form('raptor_datalayer_edit_config_form_builder');
}

function raptor_datalayer_edit_config_form_builder($form, &$form_state)
{
    $oPI = new \raptor\EditDatalayerConfigPage();
    $form = array();
    $disabled = false;
    $myvalues = array();    //No values for this one.
    return $oPI->getForm($form, $form_state, $disabled, $myvalues);
}

function raptor_datalayer_getdaoruntimemetrics_form() 
{
    return drupal_get_form('raptor_datalayer_getdaoruntimemetrics_form_builder');
}

function raptor_datalayer_getdaoruntimemetrics_form_builder($form, &$form_state)
{
    $oPI = new \raptor\EhrDaoRuntimeMetrics();
    $oPI->debug();
    return array();
    
    $form = array();
    $disabled = false;
    $myvalues = array();    //No values for this one.
    return $oPI->getForm($form, $form_state, $disabled, $myvalues);
}

