<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by SAN Business Consultants for RAPTOR phase 2
 * Open Source VA Innovation Project 2011-2014
 * VA Innovator: Dr. Jonathan Medverd
 * SAN Implementation: Andrew Casertano, Frank Font, et al
 * Contacts: acasertano@sanbusinessconsultants.com, ffont@sanbusinessconsultants.com
 * ------------------------------------------------------------------------------------
 *  
 * A workflow integration module for the RAPTOR application. 
 *
 */

function raptor_workflow_help($path, $arg) 
{
  switch ($path)
  {
    case "admin/help#raptor_workflow":
        return '<p>'.  t("Integrates workflow management and metadata into the RAPTOR package.") .'</p>';
        break;
  }
}

function raptor_workflow_menu() 
{
    $items = array();
    //NOTHING
    return $items;
}

