<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by SAN Business Consultants for RAPTOR phase 2
 * Open Source VA Innovation Project 2011-2015
 * VA Innovator: Dr. Jonathan Medverd
 * SAN Implementation: Andrew Casertano, Frank Font, et al
 * Contacts: acasertano@sanbusinessconsultants.com, ffont@sanbusinessconsultants.com
 * ------------------------------------------------------------------------------------
 *  
 * A language inference logic engine for the RAPTOR application. 
 *
 */

defined('RAPTOR_FORMULAS_MODULE_PATH')
    or define('RAPTOR_FORMULAS_MODULE_PATH', dirname(__FILE__)); 


function raptor_formulas_help($path, $arg) 
{
  switch ($path)
  {
    case "admin/help#raptor_formulas":
        return '<p>'.  t("Integrates formulas and inference logic used by the RAPTOR application.") .'</p>';
        break;
  }
}

function raptor_formulas_menu() 
{
    $items = array();
    //NOTHING
    return $items;
}

