<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by SAN Business Consultants for RAPTOR phase 2
 * Open Source VA Innovation Project 2011-2014
 * VA Innovator: Dr. Jonathan Medverd
 * SAN Implementation: Andrew Casertano, Frank Font, et al
 * Contacts: acasertano@sanbusinessconsultants.com, ffont@sanbusinessconsultants.com
 * ------------------------------------------------------------------------------------
 *  
 * A language inference logic engine for the RAPTOR application. 
 *
 */

function raptor_formulas_help($path, $arg) 
{
  switch ($path)
  {
    case "admin/help#raptor_formulas":
        return '<p>'.  t("Integrates formulas and inference logic used by the RAPTOR application.") .'</p>';
        break;
  }
}

function raptor_formulas_menu() 
{
    $items = array();
    
    $items['raptor/formulas/runtests'] = array(
      'title' => t('Workflow Test'),
      'page callback' => 'raptor_formulas_runtests_form',
      'access arguments' => array('access content'),
      'access callback' => TRUE,        
      'description' => t('Test formulas integration'),
      'type' => MENU_CALLBACK,
    );

    return $items;
}

function raptor_formulas_runtests_form() 
{
    return drupal_get_form("raptor_formulas_runtests_form_builder");
}

function raptor_formulas_runtests_form_builder($form, $form_state)
{
	throw new \Exception('Feature not yet implemented');
}

function raptor_formulas_runtests_form_builder_submit($form, &$form_state)
{
	throw new \Exception('Feature not yet implemented');
}


