<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by SAN Business Consultants for RAPTOR phase 2
 * Open Source VA Innovation Project 2011-2014
 * VA Innovator: Dr. Jonathan Medverd
 * SAN Implementation: Andrew Casertano, Frank Font, et al
 * Contacts: acasertano@sanbusinessconsultants.com, ffont@sanbusinessconsultants.com
 * ------------------------------------------------------------------------------------
 *  
 * The reports module for the RAPTOR application. 
 */

defined('RAPTOR_REPORTS_PATH')
    or define('RAPTOR_REPORTS_PATH', dirname(__FILE__));  

/** 
 * Implements hook_help. 
 * 
 * Displays help and module information. 
 * 
 * @param path  
 *   Which path of the site we're using to display help 
 * @param arg  
 *   Array that holds the current path as returned from arg() function 
 */
function raptor_reports_help($path, $arg) 
{
  switch ($path)
  {
    case 'admin/help#raptor_reports':
        return '<p>'. t('The reports functionality of the RAPTOR application.') .'</p>';
        break;
  }
}

function raptor_reports_menu() 
{
    module_load_include('php', 'raptor_reports', 'form/ManageReportsPage');
    
    $items = array();
    $aReportClassNames  = \raptor\ManageReportsPage::getReportsList();
    $aReports = \raptor\ManageReportsPage::getReportInstances($aReportClassNames);
    foreach($aReports as $classname=>$oReport)
    {
        //Can this user run this report?
        $name = $oReport->getName(); // . '['.$base_url.']';
        $description = $oReport->getDescription();
        $menukey = $oReport->getMenuKey();
        $items[$menukey] = array(
          'title' => t($name),
          'page callback' => 'raptor_reports_runner_form',
          'access arguments' => array('access content'),
          'access callback' => TRUE,        
          'description' => t($description),
          'type' => MENU_CALLBACK,
          'file' => "$classname.php",
          'file path' => '/sites/all/modules/raptor_reports/report/',
        );
    }
    
    $items['raptor/viewReports'] = array(
      'title' => t('View Reports'),
      'page callback' => 'raptor_reports_viewreports_form',
      'access arguments' => array('access content'),
      'access callback' => TRUE,        
      'description' => t('View Reports Form'),
      'type' => MENU_CALLBACK,
      'file' => 'ManageReportsPage.php',
      'file path' => '/sites/all/modules/raptor_reports/form/',
    );
    return $items;
}

function raptor_reports_viewreports_form() 
{
    return drupal_get_form('raptor_reports_viewreports_form_builder');
}

/**
 * Build page that allows user to launch reports
 */
function raptor_reports_viewreports_form_builder($form, &$form_state)
{
    $oPI = new \raptor\ManageReportsPage();
    $form = array();
    $disabled = FALSE;
    if(isset($form_state['values']))
    {
        $myvalues = $form_state['values'];    
    } else {
        $myvalues = array();
    }
    return $oPI->getForm($form, $form_state, $disabled, $myvalues);
}

function raptor_reports_runner_form() 
{
    return drupal_get_form('raptor_reports_runner_form_builder');
}

/**
 * Build any report
 */
function raptor_reports_runner_form_builder($form, &$form_state)
{
    $currentpath = strtolower(trim(current_path()));
    module_load_include('php', 'raptor_reports', 'form/ManageReportsPage');
    $aReportClassNames  = \raptor\ManageReportsPage::getReportsList();
    $aReports = \raptor\ManageReportsPage::getReportInstances($aReportClassNames);
    foreach($aReports as $classname=>$oReport)
    {
        $name = $oReport->getName();
        $menukey = $oReport->getMenuKey();
        if($currentpath == $menukey)
        {
            //Run this one!
            $reportstartdate='-7 days';
            $reportenddate  =NULL;
            if(isset($form_state['values']))
            {
                $myvalues = $form_state['values'];    
                if(isset($myvalues['report_start_date'])) 
                {
                    $reportstartdate=$myvalues['report_start_date'];
                }
                if(isset($myvalues['report_end_date'])) 
                {
                    $reportenddate=$myvalues['report_end_date'];
                }
            }
            $form = array();
            $disabled = FALSE;
            $myvalues = $oReport->getFieldValues($reportstartdate,$reportenddate);
            return $oReport->getForm($form, $form_state, $disabled, $myvalues);
        }
    }
    throw new \Exception("Did NOT find a report to run at path=[$currentpath]");
}

/**
 * Build any submitted report
 */
function raptor_reports_runner_form_builder_submit($form, &$form_state) 
{
    $currentpath = strtolower(trim(current_path()));
    module_load_include('php', 'raptor_reports', 'form/ManageReportsPage');
    $aReportClassNames  = \raptor\ManageReportsPage::getReportsList();
    $aReports = \raptor\ManageReportsPage::getReportInstances($aReportClassNames);
    foreach($aReports as $classname=>$oReport)
    {
        $name = $oReport->getName();
        $menukey = $oReport->getMenuKey();
        if($currentpath == $menukey)
        {
            //Run this one!
            $form_state['rebuild'] = TRUE;
        }
    }
}
