<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by SAN Business Consultants for RAPTOR phase 2
 * Open Source VA Innovation Project 2011-2015
 * VA Innovator: Dr. Jonathan Medverd
 * SAN Implementation: Andrew Casertano, Frank Font, et al
 * Contacts: acasertano@sanbusinessconsultants.com, ffont@sanbusinessconsultants.com
 * ------------------------------------------------------------------------------------
 *  
 * A graph integration module for the RAPTOR application. 
 *
 */

function raptor_graph_help($path, $arg) 
{
  switch ($path)
  {
    case "admin/help#raptor_graph":
        return '<p>'.  t("Integrates the graph package.") .'</p>';
        break;
  }
}

function raptor_graph_menu() 
{
    $items = array();
    //NOTHING
    return $items;
}
