<?php

defined('QA_DEFS_VERSION_INFO')
    or define('QA_DEFS_VERSION_INFO', 'UAT 20150707.1');

/*
 * These are QA scoring specific settings
 */

//QA Scoring terminology
defined('QA_SCORE_TERM_0')
    or define('QA_SCORE_TERM_0', 'Not Evaluated');
defined('QA_SCORE_TERM_1')
    or define('QA_SCORE_TERM_1', 'Needs significant improvement');
defined('QA_SCORE_TERM_2')
    or define('QA_SCORE_TERM_2', 'Needs improvement');
defined('QA_SCORE_TERM_3')
    or define('QA_SCORE_TERM_3', 'Satisfactory');
defined('QA_SCORE_TERM_4')
    or define('QA_SCORE_TERM_4', 'Very good');
defined('QA_SCORE_TERM_5')
    or define('QA_SCORE_TERM_5', 'Outstanding');
