<?php

defined("VISTA_DEFS_VERSION_INFO")
    or define("VISTA_DEFS_VERSION_INFO", 'Standard 20150526.1');

/*
 * These are VISTA specific settings not expected to change by site
 * NOTE: The site number is declared in instance specific config.
 */

defined('VISTA_NOTE_TITLE_RAPTOR_GENERAL')
    or define('VISTA_NOTE_TITLE_RAPTOR_GENERAL', 'RAPTOR NOTE');

defined('VISTA_NOTE_TITLE_RAPTOR_SAFETY_CKLST')
    or define('VISTA_NOTE_TITLE_RAPTOR_SAFETY_CKLST', 'RAPTOR SAFETY CHECKLIST');





