<?php

defined("VISTA_DEFS_VERSION_INFO")
    or define("VISTA_DEFS_VERSION_INFO", '20141015.1');

/*
 * These are VISTA specific settings
 */

defined("VISTA_NOTEIEN_RAPTOR_GENERAL")
    or define("VISTA_NOTEIEN_RAPTOR_GENERAL", '142');

defined("VISTA_NOTEIEN_RAPTOR_SAFETY_CKLST")
    or define("VISTA_NOTEIEN_RAPTOR_SAFETY_CKLST", '149');

defined("VISTA_SITE")
    or define("VISTA_SITE", '500');

