name = RAPTOR Worklist
description = The RAPTOR worklist layout
template = worklist-layout
preview = preview.png

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; ========================================
; Scripts
; ========================================
scripts[] = js/jquery-ui-1.10.3.min.js
scripts[] = js/modernizr-2.5.3.min.js
scripts[] = js/jquery.dataTables.js
scripts[] = js/worklist.js